fixes issue #4
danielmichaels/http-tracer pull request #39
Opened 2021-10-02 03:02 UTC by haydencordeiro

2021-10-02 21:25 UTC, danielmichaels requested changes
Thanks for the PR.

I have added some comments to the code and things to fix up - nothing major.

As a rule, whenever I raise a PR with another project, I like to include a detailed description of the problem I am solving with links to any issues. In this case, a segue to our conversation in #4 would have been a great starter. This is especially important on projects where multiple maintainers are present - the person reviewing this may not know of the conversation in the issue tracker. Lastly, an empty comment field on a bigger project is a pretty quick way to get your PR ignored - without context as to why this exists many maintainers simply do not have the time to reverse engineer the *why*.

2021-10-02 21:25 UTC, danielmichaels commented on tracer/main.py
> +import sys
This is already imported on line 5.

2021-10-02 21:25 UTC, danielmichaels commented on tracer/main.py
> +    if(output):
In python, for a single `if` you do not need parenthesis. 

Do this instead

```python
if output:
```

2021-10-02 21:25 UTC, danielmichaels commented on tracer/main.py
> +        sys.stdout = open(output[0], 'w')
I can see what you're doing here but why is it `output[0]`. It's not immediately apparent what `output[0]` is both as a data structure and its implementation.

Is `output[0]` a string, or list?

2021-10-03 18:28 UTC, haydencordeiro commented on tracer/main.py
> +import sys
Really sorry will look into it.

2021-10-31 09:02 UTC, danielmichaels approved these changes

2021-10-31 09:02 UTC, danielmichaels commented
Thank you for your contribution.

2021-10-31 09:02 UTC, merged